import java.util.Random;
import java.util.Scanner;

public class java_Rock_Paper_Scissor_Game {
    public static void main(String[] args) {
        System.out.println("It's Your turn, \nPlease choose your choice : ");
        Scanner sc=new Scanner(System.in);
        Random rm = new Random();

//        System.out.println("Random no Generated by Computer is");
//        int a = rm.nextInt(1,4) % 10;
//        System.out.println("User Input is");
//        int b =sc.nextInt();

        int i = 1;
        while(i <= 4){
            int Your_Turn,Computer_Turn;
            Your_Turn = sc.nextInt(3);
            //Computer is giving the input.
            Computer_Turn = rm.nextInt(3);

            System.out.println("You choosed : ");
            switch(Your_Turn) {
                case 0:
                    System.out.println("Rock");
                    break;
                case 1:
                    System.out.println("Paper");
                    break;
                case 2:
                    System.out.println("Scissor");
                    break;
            }
            System.out.println("Computer choosed : ");
            if(Computer_Turn == 0) {
                System.out.println("Rock");
            } else if(Computer_Turn == 1){
                System.out.println("Paper");
            } else if(Computer_Turn == 2){
                System.out.println("Scissor");
            }

            System.out.println("Here is the winner : ");
            if(Your_Turn == 0 && Computer_Turn == 1) {
                System.out.println("Oops! The computer won. Better luck next time");
            } else if(Your_Turn == 1 && Computer_Turn == 2) {
                System.out.println("Oops! The computer won. Better luck next time");
            } else if(Your_Turn == 2 && Computer_Turn == 0) {
                System.out.println("Oops! The computer won. Better luck next time");
            } else if(Your_Turn == 1 && Computer_Turn == 0) {
                System.out.println("Congragulations! You won!");
            } else if(Your_Turn == 2 && Computer_Turn == 1) {
                System.out.println("Congragulations! You won!");
            } else if(Your_Turn == 0 && Computer_Turn == 2) {
                System.out.println("Congragulations! You won!");
            } else if(Your_Turn == 0 && Computer_Turn == 0 || Your_Turn == 1 && Computer_Turn == 1 || Your_Turn == 2 && Computer_Turn == 2) {
                System.out.println("Sorry, the match is drawn. Please play again.");
            }
            i++;
        }
    }
}




